### ISSUE TITLE
Error importing ResNet50 

### ISSUE THREAD

**Issue by ncarboni** [damoncrockett/ivpy#90]
I add some issues importing resnet in tutorial number 5 ('tutorial5_extract-reduce-cluster') in MacOS Monterey 12 (python 3.9)
https://github.com/damoncrockett/ivpy/blob/64d9447a5a7b406c7abe3ae024d1c4ea034091cd/src/ivpy/extract.py#L19

Replacing the above line with
`from tensorflow.keras.applications import ResNet50`
fixed the problem for me

**Comment by damoncrockett** [comment]
Thanks @ncarboni ! Yeah this worked on older versions of keras/tf. I've updated the import line.
