### ISSUE TITLE
Unsupported operand type(s) for 'tuple' and 'int'

### ISSUE THREAD

**Issue by rdrainville** [damoncrockett/ivpy#93]
Going through the final step in tutorial number 4 (scatter) to create a polar visualisation of brightness & hue for each flower name throws up an error: 

unsupported operand type(s) for -: 'tuple' and 'int'

Lines of code highlighted are 

- plot.py, line 302: plotlist = [_scatter(**facet) for facet in facetlist]
- plottools.py, line 226: x,y,phis = _scalepol(xcol,ycol,xdomain,ydomain,side,thumb)
- plottools.py, line 328: pasterange = side - thumb # otherwise will cut off extremes

I'm running latest ivpy on Python 3.9.13, pip 22.1.1, and all the latest versions of the required & recommended dependencies

**Comment by damoncrockett** [comment]
Thanks @rdrainville ! This should be fixed now (I'm able to run that tutorial without error). This issue arose from changing the datatype for "side" (from int to tuple) to support having montages with unequal sides, but I hadn't cleaned up all the downstream uses of it!
